#!/usr/bin/env bash
#
# publish.sh — the "ready for the public" GitHub publish.
# Run from the app folder when the app is DONE:   ./publish.sh
#
# Order:
#   1. SECRET SCAN  — HARD GATE. Aborts if anything sensitive would be committed.
#   2. PUSH         — create the PUBLIC GitHub repo (first run) + push.
#
# The SMART pre-steps (write the README prose, GENERATE THE HERO/AD IMAGE via
# the gpt-image-design skill, remove unused files via knip) are done by Claude
# in-session BEFORE this — see the "Publishing" checklist in CLAUDE.md. This
# script only does the deterministic, safety-critical parts. (No auto-screenshot:
# the showable image is a generated SaaS product mockup at public/hero.png, not
# a headless capture — many apps don't screenshot well and a mockup shows better.)

set -euo pipefail

REPO="$(basename "$(pwd)")"

# ---------- 1. SECRET SCAN (hard gate) ----------
# Scans STAGED content (before any commit), so secrets can't even enter a commit.
# TWO engines run, and EITHER one trips the gate:
#   (a) native grep — covers project-specific creds that scanner rulesets miss,
#       notably Supabase's NEW sb_secret_/sb_publishable_ key format (verified
#       2026-06: betterleaks has no rule for these yet — would let them through).
#   (b) betterleaks — broad, maintained ruleset (Stripe/AWS/GitHub/etc.).
#       No --validation flag => ZERO network calls.
echo "==> Secret scan (gate)..."
git add -A   # stage exactly what would be committed (.gitignore excludes .env.local)
FAIL=0

# A tracked real .env file (not *.example) is an automatic fail.
ENV_TRACKED="$(git ls-files --cached | grep -E '(^|/)\.env($|\.)' | grep -v '\.example$' || true)"
if [ -n "$ENV_TRACKED" ]; then
  echo "  [x] real env file is tracked:"; echo "$ENV_TRACKED" | sed 's/^/      /'; FAIL=1
fi

# (a) native scan — full staged content.
# Tuned to the secrets MOST likely in this AI challenge that scanner rulesets
# miss (verified 2026-06 — gitleaks AND betterleaks both miss Supabase sb_* and
# OpenAI/Anthropic sk- keys on test values): Supabase keys + URL, OpenAI/Anthropic
# (sk-, sk-proj-, sk-ant-), Google, JWTs, AWS, Stripe, private keys.
PATTERNS='sb_secret_[A-Za-z0-9]{16,}|sb_publishable_[A-Za-z0-9]{16,}|GOCSPX-[A-Za-z0-9_-]{10,}|eyJ[A-Za-z0-9_-]{18,}\.[A-Za-z0-9_-]{18,}|-----BEGIN [A-Z ]*PRIVATE KEY-----|AKIA[0-9A-Z]{16}|[a-z0-9]{20}\.supabase\.co|SERVICE_ROLE|sk-[A-Za-z0-9_-]{24,}|sk_live_[A-Za-z0-9]{16,}'
# Exclude the scanner scripts themselves — they contain the pattern definitions
# (e.g. the literal "SERVICE_ROLE"), which would otherwise self-flag.
HITS="$(git grep --cached -nIE "$PATTERNS" -- ':!publish.sh' ':!backup.sh' 2>/dev/null || true)"
if [ -n "$HITS" ]; then
  echo "  [x] native scan flagged:"; echo "$HITS" | sed 's/^/      /'; FAIL=1
fi

# (b) betterleaks — broad ruleset, additive.
if command -v betterleaks >/dev/null 2>&1; then
  if ! betterleaks git . --staged --no-banner --redact >/tmp/bl-scan.out 2>&1; then
    echo "  [x] betterleaks flagged (redacted):"; tail -20 /tmp/bl-scan.out | sed 's/^/      /'; FAIL=1
  fi
else
  echo "  (note: betterleaks not installed — running native scan only)"
fi

if [ "$FAIL" -ne 0 ]; then
  echo ""
  echo "  ABORTING — sensitive content would be published. Move secrets into"
  echo "  .env.local (gitignored), read them via process.env, then re-run ./publish.sh."
  exit 1
fi
echo "  clean — nothing sensitive staged (native + betterleaks)."

# ---------- 2. PUSH (public repo) ----------
# Note: the showable image (public/hero.png) is generated by Claude in-session
# BEFORE this script (gpt-image-design skill) and embedded at the top of the
# README — there is no headless screenshot step.
echo "==> Publishing to GitHub..."
git add -A
[ -n "$(git status --porcelain)" ] && git commit -q -m "Publish: ${REPO}"
if git remote get-url origin >/dev/null 2>&1; then
  git push -q origin main
  echo "  pushed -> $(git remote get-url origin)"
else
  gh repo create "$REPO" --public --source=. --remote=origin --push
fi

echo ""
echo "  Published: https://github.com/Still-InFrame/${REPO}"
echo "  Tracker:   https://www.100dayaichallenge.com/share/savion"
